language: haxe
haxe:
    - development
    - "3.1.3"

env:
    global:
        - PACKAGE="Haxe"
    matrix:
        # - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests